name: 'smart_traffic'
version: '1.0.0'
config-version: 2

profile: 'smart_traffic'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# staging = light cleaning (views);  marts = business aggregates (tables)
models:
  smart_traffic:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
